import { TextProps } from './Text';

export declare function useText(props: TextProps): {
    role: import('./Text').TextRole | undefined;
    Element: keyof JSX.IntrinsicElements;
    children: import('../../../node_modules/react').ReactNode;
    className: string;
    style: import('../../../node_modules/react').CSSProperties;
    defaultChecked?: boolean | undefined;
    defaultValue?: string | number | readonly string[] | undefined;
    suppressContentEditableWarning?: boolean | undefined;
    suppressHydrationWarning?: boolean | undefined;
    accessKey?: string | undefined;
    autoFocus?: boolean | undefined;
    contentEditable?: "inherit" | (boolean | "false" | "true") | "plaintext-only" | undefined;
    contextMenu?: string | undefined;
    dir?: string | undefined;
    draggable?: (boolean | "false" | "true") | undefined;
    hidden?: boolean | undefined;
    id?: string | undefined;
    lang?: string | undefined;
    nonce?: string | undefined;
    slot?: string | undefined;
    spellCheck?: (boolean | "false" | "true") | undefined;
    tabIndex?: number | undefined;
    title?: string | undefined;
    translate?: "yes" | "no" | undefined;
    radioGroup?: string | undefined;
    about?: string | undefined;
    content?: string | undefined;
    datatype?: string | undefined;
    inlist?: any;
    prefix?: string | undefined;
    property?: string | undefined;
    rel?: string | undefined;
    resource?: string | undefined;
    rev?: string | undefined;
    typeof?: string | undefined;
    vocab?: string | undefined;
    autoCapitalize?: string | undefined;
    autoCorrect?: string | undefined;
    autoSave?: string | undefined;
    itemProp?: string | undefined;
    itemScope?: boolean | undefined;
    itemType?: string | undefined;
    itemID?: string | undefined;
    itemRef?: string | undefined;
    results?: number | undefined;
    security?: string | undefined;
    unselectable?: "on" | "off" | undefined;
    inputMode?: "search" | "none" | "text" | "tel" | "url" | "email" | "numeric" | "decimal" | undefined;
    is?: string | undefined;
    "aria-activedescendant"?: string | undefined;
    "aria-atomic"?: (boolean | "false" | "true") | undefined;
    "aria-autocomplete"?: "none" | "both" | "inline" | "list" | undefined;
    "aria-braillelabel"?: string | undefined;
    "aria-brailleroledescription"?: string | undefined;
    "aria-busy"?: (boolean | "false" | "true") | undefined;
    "aria-checked"?: boolean | "mixed" | "false" | "true" | undefined;
    "aria-colcount"?: number | undefined;
    "aria-colindex"?: number | undefined;
    "aria-colindextext"?: string | undefined;
    "aria-colspan"?: number | undefined;
    "aria-controls"?: string | undefined;
    "aria-current"?: boolean | "page" | "false" | "true" | "time" | "step" | "location" | "date" | undefined;
    "aria-describedby"?: string | undefined;
    "aria-description"?: string | undefined;
    "aria-details"?: string | undefined;
    "aria-disabled"?: (boolean | "false" | "true") | undefined;
    "aria-dropeffect"?: "link" | "none" | "copy" | "move" | "execute" | "popup" | undefined;
    "aria-errormessage"?: string | undefined;
    "aria-expanded"?: (boolean | "false" | "true") | undefined;
    "aria-flowto"?: string | undefined;
    "aria-grabbed"?: (boolean | "false" | "true") | undefined;
    "aria-haspopup"?: boolean | "menu" | "listbox" | "grid" | "false" | "true" | "dialog" | "tree" | undefined;
    "aria-hidden"?: (boolean | "false" | "true") | undefined;
    "aria-invalid"?: boolean | "false" | "true" | "grammar" | "spelling" | undefined;
    "aria-keyshortcuts"?: string | undefined;
    "aria-label"?: string | undefined;
    "aria-labelledby"?: string | undefined;
    "aria-level"?: number | undefined;
    "aria-live"?: "off" | "assertive" | "polite" | undefined;
    "aria-modal"?: (boolean | "false" | "true") | undefined;
    "aria-multiline"?: (boolean | "false" | "true") | undefined;
    "aria-multiselectable"?: (boolean | "false" | "true") | undefined;
    "aria-orientation"?: "horizontal" | "vertical" | undefined;
    "aria-owns"?: string | undefined;
    "aria-placeholder"?: string | undefined;
    "aria-posinset"?: number | undefined;
    "aria-pressed"?: boolean | "mixed" | "false" | "true" | undefined;
    "aria-readonly"?: (boolean | "false" | "true") | undefined;
    "aria-relevant"?: "all" | "text" | "additions" | "additions removals" | "additions text" | "removals" | "removals additions" | "removals text" | "text additions" | "text removals" | undefined;
    "aria-required"?: (boolean | "false" | "true") | undefined;
    "aria-roledescription"?: string | undefined;
    "aria-rowcount"?: number | undefined;
    "aria-rowindex"?: number | undefined;
    "aria-rowindextext"?: string | undefined;
    "aria-rowspan"?: number | undefined;
    "aria-selected"?: (boolean | "false" | "true") | undefined;
    "aria-setsize"?: number | undefined;
    "aria-sort"?: "none" | "ascending" | "descending" | "other" | undefined;
    "aria-valuemax"?: number | undefined;
    "aria-valuemin"?: number | undefined;
    "aria-valuenow"?: number | undefined;
    "aria-valuetext"?: string | undefined;
    dangerouslySetInnerHTML?: {
        __html: string | TrustedHTML;
    } | undefined;
    onCopy?: import('../../../node_modules/react').ClipboardEventHandler<HTMLElement> | undefined;
    onCopyCapture?: import('../../../node_modules/react').ClipboardEventHandler<HTMLElement> | undefined;
    onCut?: import('../../../node_modules/react').ClipboardEventHandler<HTMLElement> | undefined;
    onCutCapture?: import('../../../node_modules/react').ClipboardEventHandler<HTMLElement> | undefined;
    onPaste?: import('../../../node_modules/react').ClipboardEventHandler<HTMLElement> | undefined;
    onPasteCapture?: import('../../../node_modules/react').ClipboardEventHandler<HTMLElement> | undefined;
    onCompositionEnd?: import('../../../node_modules/react').CompositionEventHandler<HTMLElement> | undefined;
    onCompositionEndCapture?: import('../../../node_modules/react').CompositionEventHandler<HTMLElement> | undefined;
    onCompositionStart?: import('../../../node_modules/react').CompositionEventHandler<HTMLElement> | undefined;
    onCompositionStartCapture?: import('../../../node_modules/react').CompositionEventHandler<HTMLElement> | undefined;
    onCompositionUpdate?: import('../../../node_modules/react').CompositionEventHandler<HTMLElement> | undefined;
    onCompositionUpdateCapture?: import('../../../node_modules/react').CompositionEventHandler<HTMLElement> | undefined;
    onFocus?: import('../../../node_modules/react').FocusEventHandler<HTMLElement> | undefined;
    onFocusCapture?: import('../../../node_modules/react').FocusEventHandler<HTMLElement> | undefined;
    onBlur?: import('../../../node_modules/react').FocusEventHandler<HTMLElement> | undefined;
    onBlurCapture?: import('../../../node_modules/react').FocusEventHandler<HTMLElement> | undefined;
    onChange?: import('../../../node_modules/react').FormEventHandler<HTMLElement> | undefined;
    onChangeCapture?: import('../../../node_modules/react').FormEventHandler<HTMLElement> | undefined;
    onBeforeInput?: import('../../../node_modules/react').FormEventHandler<HTMLElement> | undefined;
    onBeforeInputCapture?: import('../../../node_modules/react').FormEventHandler<HTMLElement> | undefined;
    onInput?: import('../../../node_modules/react').FormEventHandler<HTMLElement> | undefined;
    onInputCapture?: import('../../../node_modules/react').FormEventHandler<HTMLElement> | undefined;
    onReset?: import('../../../node_modules/react').FormEventHandler<HTMLElement> | undefined;
    onResetCapture?: import('../../../node_modules/react').FormEventHandler<HTMLElement> | undefined;
    onSubmit?: import('../../../node_modules/react').FormEventHandler<HTMLElement> | undefined;
    onSubmitCapture?: import('../../../node_modules/react').FormEventHandler<HTMLElement> | undefined;
    onInvalid?: import('../../../node_modules/react').FormEventHandler<HTMLElement> | undefined;
    onInvalidCapture?: import('../../../node_modules/react').FormEventHandler<HTMLElement> | undefined;
    onLoad?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onLoadCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onError?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onErrorCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onKeyDown?: import('../../../node_modules/react').KeyboardEventHandler<HTMLElement> | undefined;
    onKeyDownCapture?: import('../../../node_modules/react').KeyboardEventHandler<HTMLElement> | undefined;
    onKeyPress?: import('../../../node_modules/react').KeyboardEventHandler<HTMLElement> | undefined;
    onKeyPressCapture?: import('../../../node_modules/react').KeyboardEventHandler<HTMLElement> | undefined;
    onKeyUp?: import('../../../node_modules/react').KeyboardEventHandler<HTMLElement> | undefined;
    onKeyUpCapture?: import('../../../node_modules/react').KeyboardEventHandler<HTMLElement> | undefined;
    onAbort?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onAbortCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onCanPlay?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onCanPlayCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onCanPlayThrough?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onCanPlayThroughCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onDurationChange?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onDurationChangeCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onEmptied?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onEmptiedCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onEncrypted?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onEncryptedCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onEnded?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onEndedCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onLoadedData?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onLoadedDataCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onLoadedMetadata?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onLoadedMetadataCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onLoadStart?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onLoadStartCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onPause?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onPauseCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onPlay?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onPlayCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onPlaying?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onPlayingCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onProgress?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onProgressCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onRateChange?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onRateChangeCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onResize?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onResizeCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onSeeked?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onSeekedCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onSeeking?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onSeekingCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onStalled?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onStalledCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onSuspend?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onSuspendCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onTimeUpdate?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onTimeUpdateCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onVolumeChange?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onVolumeChangeCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onWaiting?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onWaitingCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onAuxClick?: import('../../../node_modules/react').MouseEventHandler<HTMLElement> | undefined;
    onAuxClickCapture?: import('../../../node_modules/react').MouseEventHandler<HTMLElement> | undefined;
    onClick?: import('../../../node_modules/react').MouseEventHandler<HTMLElement> | undefined;
    onClickCapture?: import('../../../node_modules/react').MouseEventHandler<HTMLElement> | undefined;
    onContextMenu?: import('../../../node_modules/react').MouseEventHandler<HTMLElement> | undefined;
    onContextMenuCapture?: import('../../../node_modules/react').MouseEventHandler<HTMLElement> | undefined;
    onDoubleClick?: import('../../../node_modules/react').MouseEventHandler<HTMLElement> | undefined;
    onDoubleClickCapture?: import('../../../node_modules/react').MouseEventHandler<HTMLElement> | undefined;
    onDrag?: import('../../../node_modules/react').DragEventHandler<HTMLElement> | undefined;
    onDragCapture?: import('../../../node_modules/react').DragEventHandler<HTMLElement> | undefined;
    onDragEnd?: import('../../../node_modules/react').DragEventHandler<HTMLElement> | undefined;
    onDragEndCapture?: import('../../../node_modules/react').DragEventHandler<HTMLElement> | undefined;
    onDragEnter?: import('../../../node_modules/react').DragEventHandler<HTMLElement> | undefined;
    onDragEnterCapture?: import('../../../node_modules/react').DragEventHandler<HTMLElement> | undefined;
    onDragExit?: import('../../../node_modules/react').DragEventHandler<HTMLElement> | undefined;
    onDragExitCapture?: import('../../../node_modules/react').DragEventHandler<HTMLElement> | undefined;
    onDragLeave?: import('../../../node_modules/react').DragEventHandler<HTMLElement> | undefined;
    onDragLeaveCapture?: import('../../../node_modules/react').DragEventHandler<HTMLElement> | undefined;
    onDragOver?: import('../../../node_modules/react').DragEventHandler<HTMLElement> | undefined;
    onDragOverCapture?: import('../../../node_modules/react').DragEventHandler<HTMLElement> | undefined;
    onDragStart?: import('../../../node_modules/react').DragEventHandler<HTMLElement> | undefined;
    onDragStartCapture?: import('../../../node_modules/react').DragEventHandler<HTMLElement> | undefined;
    onDrop?: import('../../../node_modules/react').DragEventHandler<HTMLElement> | undefined;
    onDropCapture?: import('../../../node_modules/react').DragEventHandler<HTMLElement> | undefined;
    onMouseDown?: import('../../../node_modules/react').MouseEventHandler<HTMLElement> | undefined;
    onMouseDownCapture?: import('../../../node_modules/react').MouseEventHandler<HTMLElement> | undefined;
    onMouseEnter?: import('../../../node_modules/react').MouseEventHandler<HTMLElement> | undefined;
    onMouseLeave?: import('../../../node_modules/react').MouseEventHandler<HTMLElement> | undefined;
    onMouseMove?: import('../../../node_modules/react').MouseEventHandler<HTMLElement> | undefined;
    onMouseMoveCapture?: import('../../../node_modules/react').MouseEventHandler<HTMLElement> | undefined;
    onMouseOut?: import('../../../node_modules/react').MouseEventHandler<HTMLElement> | undefined;
    onMouseOutCapture?: import('../../../node_modules/react').MouseEventHandler<HTMLElement> | undefined;
    onMouseOver?: import('../../../node_modules/react').MouseEventHandler<HTMLElement> | undefined;
    onMouseOverCapture?: import('../../../node_modules/react').MouseEventHandler<HTMLElement> | undefined;
    onMouseUp?: import('../../../node_modules/react').MouseEventHandler<HTMLElement> | undefined;
    onMouseUpCapture?: import('../../../node_modules/react').MouseEventHandler<HTMLElement> | undefined;
    onSelect?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onSelectCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLElement> | undefined;
    onTouchCancel?: import('../../../node_modules/react').TouchEventHandler<HTMLElement> | undefined;
    onTouchCancelCapture?: import('../../../node_modules/react').TouchEventHandler<HTMLElement> | undefined;
    onTouchEnd?: import('../../../node_modules/react').TouchEventHandler<HTMLElement> | undefined;
    onTouchEndCapture?: import('../../../node_modules/react').TouchEventHandler<HTMLElement> | undefined;
    onTouchMove?: import('../../../node_modules/react').TouchEventHandler<HTMLElement> | undefined;
    onTouchMoveCapture?: import('../../../node_modules/react').TouchEventHandler<HTMLElement> | undefined;
    onTouchStart?: import('../../../node_modules/react').TouchEventHandler<HTMLElement> | undefined;
    onTouchStartCapture?: import('../../../node_modules/react').TouchEventHandler<HTMLElement> | undefined;
    onPointerDown?: import('../../../node_modules/react').PointerEventHandler<HTMLElement> | undefined;
    onPointerDownCapture?: import('../../../node_modules/react').PointerEventHandler<HTMLElement> | undefined;
    onPointerMove?: import('../../../node_modules/react').PointerEventHandler<HTMLElement> | undefined;
    onPointerMoveCapture?: import('../../../node_modules/react').PointerEventHandler<HTMLElement> | undefined;
    onPointerUp?: import('../../../node_modules/react').PointerEventHandler<HTMLElement> | undefined;
    onPointerUpCapture?: import('../../../node_modules/react').PointerEventHandler<HTMLElement> | undefined;
    onPointerCancel?: import('../../../node_modules/react').PointerEventHandler<HTMLElement> | undefined;
    onPointerCancelCapture?: import('../../../node_modules/react').PointerEventHandler<HTMLElement> | undefined;
    onPointerEnter?: import('../../../node_modules/react').PointerEventHandler<HTMLElement> | undefined;
    onPointerLeave?: import('../../../node_modules/react').PointerEventHandler<HTMLElement> | undefined;
    onPointerOver?: import('../../../node_modules/react').PointerEventHandler<HTMLElement> | undefined;
    onPointerOverCapture?: import('../../../node_modules/react').PointerEventHandler<HTMLElement> | undefined;
    onPointerOut?: import('../../../node_modules/react').PointerEventHandler<HTMLElement> | undefined;
    onPointerOutCapture?: import('../../../node_modules/react').PointerEventHandler<HTMLElement> | undefined;
    onGotPointerCapture?: import('../../../node_modules/react').PointerEventHandler<HTMLElement> | undefined;
    onGotPointerCaptureCapture?: import('../../../node_modules/react').PointerEventHandler<HTMLElement> | undefined;
    onLostPointerCapture?: import('../../../node_modules/react').PointerEventHandler<HTMLElement> | undefined;
    onLostPointerCaptureCapture?: import('../../../node_modules/react').PointerEventHandler<HTMLElement> | undefined;
    onScroll?: import('../../../node_modules/react').UIEventHandler<HTMLElement> | undefined;
    onScrollCapture?: import('../../../node_modules/react').UIEventHandler<HTMLElement> | undefined;
    onWheel?: import('../../../node_modules/react').WheelEventHandler<HTMLElement> | undefined;
    onWheelCapture?: import('../../../node_modules/react').WheelEventHandler<HTMLElement> | undefined;
    onAnimationStart?: import('../../../node_modules/react').AnimationEventHandler<HTMLElement> | undefined;
    onAnimationStartCapture?: import('../../../node_modules/react').AnimationEventHandler<HTMLElement> | undefined;
    onAnimationEnd?: import('../../../node_modules/react').AnimationEventHandler<HTMLElement> | undefined;
    onAnimationEndCapture?: import('../../../node_modules/react').AnimationEventHandler<HTMLElement> | undefined;
    onAnimationIteration?: import('../../../node_modules/react').AnimationEventHandler<HTMLElement> | undefined;
    onAnimationIterationCapture?: import('../../../node_modules/react').AnimationEventHandler<HTMLElement> | undefined;
    onTransitionEnd?: import('../../../node_modules/react').TransitionEventHandler<HTMLElement> | undefined;
    onTransitionEndCapture?: import('../../../node_modules/react').TransitionEventHandler<HTMLElement> | undefined;
};
