import {
  animations,
  borderRadius,
  breakpoints,
  colors,
  fontFamilies,
  fontSizes,
  fontWeights,
  letterSpacings,
  lineHeights,
  opacities,
  scales,
  shadows,
  shapes,
  spacing,
  transforms,
  transitions,
  zIndices,
} from '@/token';
import { ConfigRuKit } from './index';

export const DefaultRuKitConfig: ConfigRuKit = {
  theme: 'light',
  size: 'medium',
  fontSize: fontSizes,
  fontFamily: fontFamilies.primary,
  fontWeight: fontWeights.regular,
  lineHeight: lineHeights.medium,
  letterSpacing: letterSpacings.normal,
  color: {
    primary: colors.blue['500'],
    secondary: colors.grey['500'],
    accent: colors.green['500'],
    error: colors.red['500'],
    warning: colors.orange['500'],
  },
  spacing: spacing,
  borderRadius: borderRadius,
  breakpoints: breakpoints,
  boxShadow: shadows.medium,
  opacity: opacities,
  transition: transitions.default,
  zIndex: zIndices,
  shapes: shapes,
  scales: scales,
  transforms: transforms,
  animations: animations,
};
