import {
  animations,
  borderRadius,
  breakpoints,
  colors,
  fontFamilies,
  fontSizes,
  fontWeights,
  letterSpacings,
  lineHeights,
  opacities,
  scales,
  shadows,
  shapes,
  spacing,
  transforms,
  transitions,
  zIndices,
} from '@/token';
import { TTheme } from '@/types';
import { ConfigRuKit } from './index';

export const DefaultRuKitConfig: Record<TTheme, ConfigRuKit> = {
  light: {
    size: 'medium',
    fontSize: fontSizes,
    fontFamily: fontFamilies.primary,
    fontWeight: fontWeights.regular,
    lineHeight: lineHeights.medium,
    letterSpacing: letterSpacings.normal,
    color: {
      primary: colors.blue['500'],
      secondary: colors.grey['500'],
      accent: colors.green['500'],
      error: colors.red['500'],
      warning: colors.orange['500'],
      background: colors.white['100'],
      surface: colors.grey['100'],
      text: {
        primary: colors.grey['800'],
        secondary: colors.grey['600'],
      },
    },
    spacing: spacing,
    borderRadius: borderRadius,
    breakpoints: breakpoints,
    boxShadow: shadows.medium,
    opacity: opacities,
    transition: transitions.default,
    zIndex: zIndices,
    shapes: shapes,
    scales: scales,
    transforms: transforms,
    animations: animations,
  },
  dark: {
    size: 'medium',
    fontSize: fontSizes,
    fontFamily: fontFamilies.primary,
    fontWeight: fontWeights.regular,
    lineHeight: lineHeights.medium,
    letterSpacing: letterSpacings.normal,
    color: {
      primary: colors.blue['400'],
      secondary: colors.grey['300'],
      accent: colors.green['400'],
      error: colors.red['400'],
      warning: colors.orange['400'],
      background: colors.grey['900'],
      surface: colors.grey['800'],
      text: {
        primary: colors.grey['100'],
        secondary: colors.grey['300'],
      },
    },
    spacing: spacing,
    borderRadius: borderRadius,
    breakpoints: breakpoints,
    boxShadow: shadows.large,
    opacity: opacities,
    transition: transitions.default,
    zIndex: zIndices,
    shapes: shapes,
    scales: scales,
    transforms: transforms,
    animations: animations,
  },
  highContrast: {
    size: 'medium',
    fontSize: fontSizes,
    fontFamily: fontFamilies.primary,
    fontWeight: fontWeights.bold,
    lineHeight: lineHeights.large,
    letterSpacing: letterSpacings.normal,
    color: {
      primary: colors.white['100'],
      secondary: colors.black['100'],
      accent: colors.yellow['500'],
      error: colors.red['700'],
      warning: colors.orange['700'],
      background: colors.black['100'],
      surface: colors.grey['800'],
      text: {
        primary: colors.white['100'],
        secondary: colors.grey['400'],
      },
    },
    spacing: spacing,
    borderRadius: borderRadius,
    breakpoints: breakpoints,
    boxShadow: shadows.large,
    opacity: opacities,
    transition: transitions.default,
    zIndex: zIndices,
    shapes: shapes,
    scales: scales,
    transforms: transforms,
    animations: animations,
  },
  protanopia: {
    size: 'medium',
    fontSize: fontSizes,
    fontFamily: fontFamilies.primary,
    fontWeight: fontWeights.regular,
    lineHeight: lineHeights.medium,
    letterSpacing: letterSpacings.normal,
    color: {
      primary: colors.blue['500'],
      secondary: colors.grey['500'],
      accent: colors.yellow['500'],
      error: colors.purple['500'],
      warning: colors.brown['500'],
      background: colors.white['100'],
      surface: colors.grey['100'],
      text: {
        primary: colors.grey['800'],
        secondary: colors.grey['600'],
      },
    },
    spacing: spacing,
    borderRadius: borderRadius,
    breakpoints: breakpoints,
    boxShadow: shadows.medium,
    opacity: opacities,
    transition: transitions.default,
    zIndex: zIndices,
    shapes: shapes,
    scales: scales,
    transforms: transforms,
    animations: animations,
  },
  deuteranopia: {
    size: 'medium',
    fontSize: fontSizes,
    fontFamily: fontFamilies.primary,
    fontWeight: fontWeights.regular,
    lineHeight: lineHeights.medium,
    letterSpacing: letterSpacings.normal,
    color: {
      primary: colors.violet['500'],
      secondary: colors.grey['500'],
      accent: colors.cyan['500'],
      error: colors.purple['500'],
      warning: colors.brown['500'],
      background: colors.white['100'],
      surface: colors.grey['100'],
      text: {
        primary: colors.grey['800'],
        secondary: colors.grey['600'],
      },
    },
    spacing: spacing,
    borderRadius: borderRadius,
    breakpoints: breakpoints,
    boxShadow: shadows.medium,
    opacity: opacities,
    transition: transitions.default,
    zIndex: zIndices,
    shapes: shapes,
    scales: scales,
    transforms: transforms,
    animations: animations,
  },
  tritanopia: {
    size: 'medium',
    fontSize: fontSizes,
    fontFamily: fontFamilies.primary,
    fontWeight: fontWeights.regular,
    lineHeight: lineHeights.medium,
    letterSpacing: letterSpacings.normal,
    color: {
      primary: colors.red['500'],
      secondary: colors.grey['500'],
      accent: colors.green['500'],
      error: colors.purple['500'],
      warning: colors.orange['500'],
      background: colors.white['100'],
      surface: colors.grey['100'],
      text: {
        primary: colors.grey['800'],
        secondary: colors.grey['600'],
      },
    },
    spacing: spacing,
    borderRadius: borderRadius,
    breakpoints: breakpoints,
    boxShadow: shadows.medium,
    opacity: opacities,
    transition: transitions.default,
    zIndex: zIndices,
    shapes: shapes,
    scales: scales,
    transforms: transforms,
    animations: animations,
  },
};