name: Deploy Storybook

on:
  push:
    branches: [main]
    paths: ['src/stories/**', 'src/components/**']

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Install and Build 🔧
        run: |
          npm install
          npm run build-storybook
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main
          FOLDER: docs-build
          CLEAN: true
          TARGET_FOLDER: docs

      - name: Change working directory
        run: cd /path/to/your/jekyll/site
        shell: bash

      # Run Jekyll build command
      - name: Build Jekyll site
        run: bundle exec jekyll build
